<<<<<<< HEAD
application: jinjaunknownnumber
=======
application: jinjacalc
>>>>>>> 9f655e56ded0adc6310c342f2e181381dee1a616
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest